env:
  browser: true
  es6: true

root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - cypress
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:cypress/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  array-bracket-spacing: error
  comma-spacing: error
  eqeqeq: error
  key-spacing: error
  keyword-spacing: error
  no-duplicate-imports: error
  no-multi-spaces: error
  no-multiple-empty-lines: error
  no-trailing-spaces: error
  no-var: error
  object-curly-spacing: error
  object-shorthand: [error, consistent]
  prefer-arrow-callback: error
  prefer-const: error
  quotes: [error, single, {avoidEscape: true}]
  semi: error
  space-before-blocks: error
  space-in-parens: error
  space-infix-ops: error
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/no-unused-vars": [error, {vars: all, args: none}]
