# Template for secret values used by the Helm files.

# Note that every secret needs to be nested below this `secret` key
# so that we can properly encode them in template/secrets.yaml.
secrets:
  # Database
  database_password:

  # S3
  s3_access_key:
  s3_secret_key:
